### ISSUE TITLE
iOS 10 Crash

### ISSUE THREAD

**Issue by dually8** [dually8/BarcodeScanner#3]
### Expected behavior
- Opening and closing the barcode scanner will not crash the app
### Actual behavior
- Opening and closing the barcode scanner crashes the app.
### Steps to reproduce the behavior
- Clone this repo `https://github.com/dually8/BarcodeScannerExample.git`
- Open and close the barcode scanner til crash occurs (usually around 3-5 open and closes)
### Additional Info
- I've spent a collective of 12 hours fighting this barcode scanner thing with no luck. Using XCode tools showed no memory leaks, no process spikes, no error messages, no nothing. The app just exits without warning or error messages. No idea what's happening. If anyone wants to take a stab at it with me, just let me know, but I've tried everything I can think of.

**Comment by dually8** [comment]
If it helps:
Before iOS 10 - https://github.com/Telerik-Verified-Plugins/BarcodeScanner/blob/3ee4e555102c8ad6a94f2cb8777010acfa4c2526/src/ios/CDVBarcodeScanner.mm

After iOS 10 - https://github.com/Telerik-Verified-Plugins/BarcodeScanner/blob/master/src/ios/CDVBarcodeScanner.mm

Library I'm using - https://github.com/TheLevelUp/ZXingObjC

**Comment by otherchirps** [comment]
I was attempting a similar approach as yourself, aiming to integrate ZXingObjC with the ios version of the phonegap-plugin-barcodescanner.  Being new to all this, couldn't quite get it going, until I stumbled over your plugin.xml, which was one of my main stumbling blocks.

Appears to be working for me on iOS 10 devices.  Started from the current plugin codebase (6.0.5), and added the current ZXingObjC files. 

Repo is over [here](https://github.com/otherchirps/phonegap-plugin-barcodescanner).  I haven't seen the sudden exits you reported (so far...).

**Comment by dually8** [comment]
thanks @otherchirps! I appreciate it. I'll see if I can get this thing working. I remember lowering the quality of the shots tended to make it crash less, but I think after something like 50 scans or so, it'll crash. I haven't had a chance to keep up with this as much as I want due to work. :(
